export const GAMES_SORT_COMPLETION_ASC = 'GAMES_SORT_COMPLETION_ASC';
export const GAMES_SORT_COMPLETION_DESC = 'GAMES_SORT_COMPLETION_DESC';
export const GAMES_SORT_NAME_ASC = 'GAMES_SORT_NAME_ASC';
export const GAMES_SORT_NAME_DESC = 'GAMES_SORT_NAME_DESC';

export const GAME_ACHIEVEMENT_SORT_LATEST = 'GAME_ACHIEVEMENT_SORT_LATEST';
export const GAME_ACHIEVEMENT_SORT_OLDEST = 'GAME_ACHIEVEMENT_SORT_OLDEST';
